### ISSUE TITLE
Empty key name error

### ISSUE THREAD

**Issue by krasnovpro** [TheArkive/JXON_ahk2#1]
I catch the error: 
![image](https://user-images.githubusercontent.com/886676/127135762-1834ffd1-632d-4aa9-8ed2-bfbf9c076d35.png)

On the empty key name: 
![image](https://user-images.githubusercontent.com/886676/127135842-3e3d6303-28d8-41a4-8969-db91e8aec80e.png)

**Comment by TheArkive** [comment]
Yes it is coded that way.

```
Line #179-180

if IsObject(k) || (k == "")
    throw Error("Invalid object key.", -1, k ? Format("<Object at 0x{:p}>", ObjPtr(obj)) : "<blank>")
```

If you want to change it remove `|| (k == "")`:

```
Line #179-180

if IsObject(k)
    throw Error("Invalid object key.", -1, k ? Format("<Object at 0x{:p}>", ObjPtr(obj)) : "<blank>")
```

The original code from coco also includes this, so I'll close this issue.
